### ISSUE TITLE
Add mobile meta tag

### ISSUE THREAD

**Issue by amyhenning** [nagashi/ceo-repository#1]
Hey Charles,

Great job with your Splurty app!

Things look great with the Bootstrap styles and fonts you added - but on mobile things don't look as good as they could be. This is a common issue with a pretty simple fix.

Google search for how you can add a "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile. Once you find a tag to add, you can add it to your application.html.erb file here:

https://github.com/nagashi/ceo-repository/blob/master/app/views/layouts/application.html.erb#L7

Let me know in the comments once you figured that step out :)

Keep up the good work!

--Amy

**Comment by nagashi** [comment]
Amy,

 

I added the following code to take care of the issue you pointed out.  Thanks by the way.  However, I pushed it out to Heroku and it looks like the pits.  Was the code not correct?

 

<meta name="viewport" content="width=device-width, initial-scale=1.0">

 

 

 

 

With gratitude,

CEO'Riley Jr.

Charles Ellis O'Riley Jr.

 

You miss 100% of the shots you don’t take – Wayne Gretzky

I never lose…either I win or I learn – Unknown

**Comment by amyhenning** [comment]
Hi Charles,

It looks like the comment you added on line 7 isn't correctly closed. 

https://github.com/nagashi/ceo-repository/blob/master/app/views/layouts/application.html.erb#L7

Try removing that line and see what happens. You can test things out on your localhost site before pushing to Heroku.

Thanks,

Amy

**Comment by nagashi** [comment]
I did test it locally but it didn’t look like that.  Was that the right piece of code to use?

 

 

 

With gratitude,

CEO'Riley Jr.

Charles Ellis O'Riley Jr.

 

You miss 100% of the shots you don’t take – Wayne Gretzky

I never lose…either I win or I learn – Unknown

**Comment by amyhenning** [comment]
Yes, the code you added on line 8 looks right. Try removing line 7. That comment tag is not closed correctly.

**Comment by nagashi** [comment]
Hi Amy,

 

I should have caught that comment section.  I took it out and sent it to Heroku again.  Tested it and it’s GOOD TO GO.  Thanks for your patience and help.

 

 

 

With gratitude,

CEO'Riley Jr.

Charles Ellis O'Riley Jr.

 

You miss 100% of the shots you don’t take – Wayne Gretzky

I never lose…either I win or I learn – Unknown

**Comment by amyhenning** [comment]
You're welcome! I'll go ahead and close this issue since things are working as expected now!
